FROM tensorflow/tensorflow:latest

# set working directory
WORKDIR /app

# Install Poetry
RUN pip install poetry

# Copy poetry related files.
COPY poetry.lock pyproject.toml /app/

# Install the dependencies
RUN poetry install --without dev test inference
