apiVersion: apps/v1
kind: Deployment
metadata:
  name: ship-detection-api
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels: 
      app: ship-detection-api
  template: 
    metadata:
      labels:
        app: demo-api-app
    spec:
      containers:
      - name: ship-detection-api
        image: ldebele/ship-detection-api:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8585