apiVersion: v1
kind: Service
metadata:
  name: ship-detection-api
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: ship-detection-api
  ports: 
    - port: 8585
      targetPort: 8585